.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. myoriginalcoin_qt test_myoriginalcoin_qt
clean: FORCE
	$(MAKE) -C .. myoriginalcoin_qt_clean test_myoriginalcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_myoriginalcoin_qt_check
myoriginalcoin-qt myoriginalcoin-qt.exe: FORCE
	 $(MAKE) -C .. myoriginalcoin_qt
